server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  JwtSecretKey: secretkey
  JwtExpireInHour: 360
  RefreshSecretKey: refreshSecretKey
  RefreshTokenExpireInHour: 3600
  CookieName: jwt-token
  ReadTimeout: 5
  WriteTimeout: 5
  SSL: false
  CtxDefaultTimeout: 12
  CSRF: true
  Debug: true
  MaxConnectionIdle: 5
  Timeout: 15
  MaxConnectionAge: 5


logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info

mysql:
  MysqlHost: mysql
  MysqlPort: 3306
  MysqlUser: app_User
  MysqlPassword: app_Password
  MysqlDbname: app
  MysqlDriver: mysql

kafka:
  Server: kafka:9092
  AuditLogServer: kafka:9092
  Username: admin
  Password: admin

opensearch:
  Server: http://opensearch:9200
  Username: elastic
  Password: app@2022
