server:
  AppVersion: 1.0.0
  Port: :5000
  PprofPort: :5555
  Mode: Development
  Debug: true
  CacheExpiryShort: 600000000000
  CacheExpiryMedium: 3600000000000
  CacheExpiryLong: 14400000000000
  CacheExpiryDayLong: 86400000000000
  HashKey: 8YivRHLzCmnwXBE7TZIRTt210ju5MnE9
  PassKey: MehrBgJkXvMxcyLUQPO7zTAb2aWX6bCwPDaU
  IvKey: MehrBgJkXvMxcyLU


logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: debug

mysql:
  MysqlHost: host.docker.internal
  MysqlPort: 4000
  MysqlUser: root
  MysqlPassword: 
  MysqlDbname: app
  MysqlDriver: mysql

# mysql:
#   MysqlHost: mysql
#   MysqlPort: 3306
#   MysqlUser: app_User
#   MysqlPassword: app_Password
#   MysqlDbname: app
#   MysqlDriver: mysql

jaeger:
  Host: localhost:6831
  ServiceName: app_service
  LogSpans: false

kafka:
  Server: kafka:9092
  AuditLogServer: kafka:9092
  Username: admin
  Password: admin

opensearch:
  Server: http://opensearch:9200
  Username: admin
  Password: admin
